### ISSUE TITLE
Unable to export projects with variations in responses

### ISSUE THREAD

**Issue by manish-95** [Botmock/botmock-bot-framework-export#31]
**Issue Overview**
While running the script, I get an error when trying to export the lg file. This is noticed in cases where the project contains alternate responses as part of the flow design.

**Steps To Reproduce**
1. Enter the required values into .env file.
2. Run the script using npm start
3. Note the error as given below

**Expected Behavior**
The script must successfully export both the .lu as well as the .lg files for the given project.

**Screenshots**
![image](https://user-images.githubusercontent.com/29098159/77649914-a1474e00-6f90-11ea-8cef-1cc4e1caed71.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - NPM Version: 6.14.2
 - Node version: v12.13.1

**Comment by nonnontrivial** [comment]
Closing since https://github.com/Botmock/botmock-bot-framework-export/pull/32 is merged and this should no longer be an issue.
